Responsive Design and CSS Frameworks: Using Bootstrap
nikoescobal/newsweek-bootstrap-clone pull request #3
Opened 2020-09-14 20:43 UTC by nikoescobal

## Newsweek Clone: Responsive Design and CSS Frameworks - Part 2 (Using Bootstrap)

In this project:
- An exact replica of [Newsweek](https://www.newsweek.com/ website) built with a mobile-first approach.
- Bootstrap's CSS classes and grid system are utilized to make the website fully responsive across all screen sizes.
- CSS flex, grid, positioning, media queries, and fluid/responsive web design principles are also applied. 
- This document validates as CSS level 3 + SVG by W3C CSS Validator and is validated by Jigsaw for HTML.

I initially struggled with this, esp. since I did this solo, but I did my best and am proud of my work. Hope you like it.

Thank you
~Nik :heart:

2020-09-15 12:34 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-15 13:18 UTC, umairarshadbutt commented
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @nikoescobal
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ]  `U.S.`,  `World Business`, `Tech & Science`, `culture`, and `Sports` sections are missing. Please add these section in the page.
- [ ] Navbar is not fixed in the clone as compared to the original page.

### Manage the spaces
|[Source Page](https://thenextweb.com/)|[Clone Page](https://rawcdn.githack.com/nikoescobal/newsweek-bootstrap-clone/16ebf8d2043029aac9959f2f7fcae2b911bb07ed/index.html)|
|:---:|:---:|
|![space-original](https://user-images.githubusercontent.com/29689273/93214530-baca9500-f77e-11ea-9dd3-a0e0c1808b19.png)|![space-clone](https://user-images.githubusercontent.com/29689273/93214563-c6b65700-f77e-11ea-9707-88a633144c1d.png)|
- [ ] Manage the content according to the original page.

### Update the current Date

|[Source Page](https://thenextweb.com/)|[Clone Page](https://rawcdn.githack.com/nikoescobal/newsweek-bootstrap-clone/16ebf8d2043029aac9959f2f7fcae2b911bb07ed/index.html)|
|:---:|:---:|
|![date-orginal](https://user-images.githubusercontent.com/29689273/93214824-17c64b00-f77f-11ea-99a7-dddeaf0c9107.png)|![date-clone](https://user-images.githubusercontent.com/29689273/93214863-2280e000-f77f-11ea-9548-42c1917f3238.png)|

- [ ] Update current date.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-15 14:09 UTC, nikoescobal commented
@umairarshadbutt Thank you for reviewing my code, and for listening to my case. As we agreed, I will be resubmitting my project as is.

2020-09-15 15:50 UTC, arslanbisharat requested changes
### Request changes
I can see you worked hard on this project but I am sorry to inform you that I cannot Approve this project because it is not completed yet.:worried:
It's okay. We are here to learn. Don't get discouraged. Work more hard.
 **Please have a look at the suggestions to get more understanding. :eyes:**

- [ ] I couldn't understand why you didn't change the date. :confused: Change to date from **Mon, Aug 31, 2020,**, to the **current date**

- [ ] Make the center static as in the original page. 

- [ ] Make your footer exactly the same as present on the original page. 

- [ ] Add image under newsletter and increase left width.

- [ ]  Please correct these
![chrome-capture (3)](https://user-images.githubusercontent.com/58504655/93233217-426ece80-f794-11ea-8e59-9b6aead1144f.jpg)

**Please make the changes and request re-review for the given project**
Stay safe:innocent:
### Happy Coding
-------------------------------------------------------------------------------------------------------------------------------------------

**Regards,
Arslan Bisharat
****slack: arslanbisharat******

2020-09-15 15:50 UTC, arslanbisharat commented on index.html
> +        <span class="text-white d-none d-lg-block ml-1">Mon, Aug 31, 2020</span>
- [ ] As requested from previous TSE, please update date

2020-09-15 15:50 UTC, arslanbisharat commented on index.html
> +    </div>
- [ ] There is a break-line on the original page that is missing in your project. 
Please have a look. 
![Your Work](https://user-images.githubusercontent.com/58504655/93228844-64198700-f78f-11ea-8317-ca2e21dd3fb7.jpg)
![original work](https://user-images.githubusercontent.com/58504655/93228901-7693c080-f78f-11ea-8954-9a6b07aa9c78.jpg)

2020-09-15 15:50 UTC, arslanbisharat commented on index.html
> +                  newsletter
- [ ] Photo is missing under newsletter as present in original page
![chrome-capture (1)](https://user-images.githubusercontent.com/58504655/93229491-13565e00-f790-11ea-8ed7-06936eefc444.jpg)

2020-09-15 15:50 UTC, arslanbisharat commented on index.html
> +                </li>
- [ ] Add l after each link. 
![chrome-capture (2)](https://user-images.githubusercontent.com/58504655/93229741-5a445380-f790-11ea-8034-b9f9987a1f3d.jpg)

2020-09-15 15:50 UTC, arslanbisharat commented on index.html
> +            <div class="my-turn order-4 position-relative d-md-none pt-4">
- [ ] Have a look at the original project. Make it static

2020-09-16 17:16 UTC, nikoescobal commented
I've implemented relevant changes. @umairarshadbutt  @arslanbisharat I'm sorry, but this request to have the date changed is not objectively useful or relevant. I don't see how this helps improve my code. 

I asked my standup teammates and other students and they all told me this was not an issue that prevented their projects from being approved. In fact, many projects had placeholders, like Lorem Ipsum for the content, including the date section.

As TSE's, you have the potential to really help students improve. I sincerely ask that you give valid and objectively useful feedback based on best-practices, and not subjective change requests that are based on your preferences. 

Thank you.

2020-09-16 18:01 UTC, javitocor requested changes
# CHANGES REQUIRED ♻️ 

Good job so far with this project 👍  but still some changes left to get approved. It is almost done, just a little bit more. ⏩ 
After all the requirements are made, re-submit the project for a new code review.

If you have any question or doubt do not hesitate to contact me on Slack.

Check my comments below 👇 

- There are still some sections left to build: US, World, Business, Tech&Science, Culture and Sports. Please add all of them 💪 
- The navigation bar should be fixed or sticky. Make it happen.
- Add the | after every li in the footer
- Change the date, it is a previous requirement.

Good luck 😄

2020-09-16 20:02 UTC, nikoescobal commented
@javitocor https://rawcdn.githack.com/nikoescobal/newsweek-bootstrap-clone/29384df0ca08c064180a6aa2a533e869dc4b06f7/index.html I'm not sure if you're looking at the correct project, because all those things are there. The navbar is sticky, there is a border after every li in the footer, and the date has been updated as well. As for the sections you mentioned, as I previously mentioned to the other TSE, the Newsweek website is constantly updating. The version I modeled my code after did not contain those sections. I don't see any reason to build them out, especially if I've already accomplished the purpose of this project, which is to utilize Bootstrap extensively.

2020-09-16 20:27 UTC, arslanbisharat commented
Hello! We are really sorry you didn't catch what we were trying to say 

- [ ] There are still some sections left to build: US, World, Business, Tech&Science, Culture, and Sports. Please add all of them 
![chrome-capture (20)](https://user-images.githubusercontent.com/58504655/93388843-c43e2500-f884-11ea-9045-712ee46a226d.jpg)
![chrome-capture (19)](https://user-images.githubusercontent.com/58504655/93388874-cf915080-f884-11ea-9c0c-e8aeef97b9d1.jpg)
![chrome-capture (18)](https://user-images.githubusercontent.com/58504655/93388887-d4560480-f884-11ea-9a72-d7e117f0e7ed.jpg)
![chrome-capture (17)](https://user-images.githubusercontent.com/58504655/93388892-d750f500-f884-11ea-983f-6887d1f3d6c2.jpg)

2020-09-16 20:48 UTC, teekaytech requested changes
# Status: Changes Required :recycle: 

**It is crystal clear that you've been so careful in implementing this project. I really love how much attention you've paid to the details. However, there's one major feature that's stopping me from approving your project. Please observe carefully and submit another review request form when you're done.**

As mentioned by the previous TSE, there's a major section missing out on your project. I will try to point it out with a detailed illustration. The section is located after Editor's Picks (_see image below_)

**Here's your copy:**
![Screenshot_2020-09-16 Newsweek Clone](https://user-images.githubusercontent.com/26856491/93390617-e5434d80-f865-11ea-8162-ed077282bd14.jpg)


**Here's source copy:**
![Screenshot_2020-09-16 Newsweek](https://user-images.githubusercontent.com/26856491/93390659-f2603c80-f865-11ea-9632-4725ccbbc211.jpg)


**I hope you now see what the previous TSE meant the issue he raised. Kindly implement the feature and resubmit for re-review.**

With respect, 
Taofeek Olalere 
GitHub: @teekaytech
Slack: @taofeekolalere

2020-09-16 21:12 UTC, nikoescobal commented
@teekaytech Thank you for the kind words. Before anything else, I'd really appreciate it if you could make a consideration for this case. As you can see in the image below, this is the version I was modeling my project after (it's also in the README)..

The Newsweek site updates quite frequently, and so these sections come and go. It is with this fact in mind that I opted not to build those sections.

The case I am trying to make is that I feel that the work I've put out is a reflection of my understanding and ability to utilize the Bootstrap framework, which is the true objective of the project. 

If you still strongly feel that I need to build out those sections, then I will do so. Hoping for your kind consideration on the matter. 

![Newsweek-screenshot](https://user-images.githubusercontent.com/62937819/93392217-fbbbca00-f8a2-11ea-94d9-353b8c32e745.jpg)

2020-09-16 21:58 UTC, teekaytech commented
> @teekaytech Thank you for the kind words. Before anything else, I'd really appreciate it if you could make a consideration for this case. As you can see in the image below, this is the version I was modeling my project after (it's also in the README)..
> 
> The Newsweek site updates quite frequently, and so these sections come and go. It is with this fact in mind that I opted not to build those sections.
> 
> The case I am trying to make is that I feel that the work I've put out is a reflection of my understanding and ability to utilize the Bootstrap framework, which is the true objective of the project.
> 
> If you still strongly feel that I need to build out those sections, then I will do so. Hoping for your kind consideration on the matter.
> 
> ![Newsweek-screenshot](https://user-images.githubusercontent.com/62937819/93392217-fbbbca00-f8a2-11ea-94d9-353b8c32e745.jpg)


Hello @nikoescobal
I totally understand your point and based on what I've seen in the project, it is clear that you understand the concepts of responsive design. I want you to know that TSEs are also students like you and as a result of that, we have a lot of things in common. Most importantly, we all follow instructions. 

For every project, there's a standard set of requirements that must be satisfied. These requirements are microverse standard which cannot be bent by any student (TSEs inclusive). For this particular project, that every section is one of the requirements that any TSE must confirm it's availability.

In summary, you will have to build the section for your project to be complete. Please take some time to implement that section and request another review. I hope you understand my explanations.

Best regards
Taofeek Olalere (@teekaytech )
**Happy coding**

2020-09-18 14:42 UTC, nikoescobal commented
I've added all the changes requested.

2020-09-19 02:22 UTC, arslanbisharat commented
### Congratulations APPROVED :clap:
Hello I can see you worked really hard on this project. I reviewed your [project](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)  and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
Now you can merge the branches and move forward with your curriculum. 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 
**Happy Coding**:smiley:
-------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) @slack: arslanbisharat

2020-09-20 14:27 UTC, merged